[cache]
  type = "file"
  basepath = "cache"

[[providers]]
  name = "osm2pgsql"
  type = "postgis"
  host = "/var/run/postgresql" # Default for Debian-based distributions
  port = 5432                     # postgis database port
  database = "gis"        # postgis database name
  user = ""
  password = ""

[[providers.layers]]
  name = "ne_water"
  geometry_fieldname = "way"
  geometry_type = "Polygon"
  sql = """
  SELECT
      ST_AsBinary(way) AS way
  FROM ne_ocean
  WHERE way && !BBOX!
  UNION ALL
  SELECT
      ST_AsBinary(way) AS way
  FROM ne_lake
  WHERE way && !BBOX!
  """

[[providers.layers]]
  name = "lz_water"
  geometry_fieldname = "way"
  geometry_type = "Polygon"
  sql = """
  SELECT
      ST_AsBinary(ST_SimplifyPreserveTopology(way, pixel_size(!ZOOM!)*.25)) AS way,
      NULL as osm_id
    FROM simplified_ocean_polygons
    WHERE way && !BBOX!
  UNION ALL
  SELECT
      ST_AsBinary(ST_SimplifyPreserveTopology(way, pixel_size(!ZOOM!)*.25)) AS way,
      osm_id
    FROM planet_osm_polygon
    WHERE way && !BBOX!
      AND (waterway = 'riverbank'
        OR landuse = 'reservoir'
        OR "natural" = 'water')
      AND way_area > pixel_area(!ZOOM!)*0.25
  """
[[providers.layers]]
  name = "water"
  geometry_fieldname = "way"
  geometry_type = "Polygon"
  sql = """
  SELECT
      ST_AsBinary(ST_SimplifyPreserveTopology(way, pixel_size(!ZOOM!)*.25)) AS way,
      NULL AS osm_id
    FROM ocean_polygons
    WHERE way && !BBOX!
  UNION ALL
  SELECT
      ST_AsBinary(ST_SimplifyPreserveTopology(way, pixel_size(!ZOOM!)*.25)) AS way,
      osm_id
    FROM planet_osm_polygon
    WHERE way && !BBOX!
      AND (waterway = 'riverbank'
        OR landuse = 'reservoir'
        OR "natural" = 'water')
      AND way_area > pixel_area(!ZOOM!)*0.25
  """

[[providers.layers]]
  name = "water_names"
  geometry_fieldname = "way"
  geometry_type = "Point"
  sql = """
  SELECT
      ST_AsBinary(ST_PointOnSurface(way)) AS way,
      osm_id,
      name,
      way_area AS area
    FROM planet_osm_polygon
    WHERE way && !BBOX!
      AND name IS NOT NULL
      AND (landuse = 'reservoir'
        OR "natural" = 'water')
      AND NOT water = 'river'
      AND way_area > pixel_area(!ZOOM!)*32*32
    ORDER BY way_area DESC
  """

[[providers.layers]]
  name = "waterways"
  geometry_fieldname = "way"
  geometry_type = "LineString"
  sql = """
  SELECT
      ST_AsBinary(ST_RemoveRepeatedPoints(way,pixel_size(!ZOOM!)*0.25)) AS way,
      waterway,
      name
    FROM planet_osm_line
    WHERE way && !BBOX!
      AND (waterway = 'river'
        OR waterway IN ('canal', 'stream') AND !ZOOM! >= 12
        OR waterway IN ('drain', 'ditch', 'wadi') AND !ZOOM! >= 14)
  """

[[providers.layers]]
  name = "landcover"
  geometry_fieldname = "way"
  geometry_type = "Polygon"
  sql = """
  SELECT
      ST_AsBinary(ST_SimplifyPreserveTopology(way, pixel_size(!ZOOM!)*.25)) AS way,
      osm_id,
      landuse,
      "natural",
      leisure
    FROM planet_osm_polygon
    WHERE way && !BBOX!
      AND (landuse IN ('industrial', 'residential', 'forest', 'grass')
        OR "natural" IN ('wood')
        OR leisure IN ('pitch', 'common', 'park', 'golf_course', 'cemetery'))
      AND way_area > pixel_area(!ZOOM!)*0.25
  """

[[providers.layers]]
  name = "parks"
  geometry_fieldname = "way"
  geometry_type = "Polygon"
  sql = """
  SELECT
      ST_AsBinary(ST_SimplifyPreserveTopology(way, pixel_size(!ZOOM!)*.25)) AS way,
      osm_id,
      leisure
    FROM planet_osm_polygon
    WHERE way && !BBOX!
      AND leisure = 'nature_reserve'
      AND way_area > pixel_area(!ZOOM!)*0.25
  """

[[providers.layers]]
  name = "ne_boundaries"
  geometry_fieldname = "way"
  geometry_type = "LineString"
  sql = """
  SELECT
      ST_AsBinary(ST_RemoveRepeatedPoints(way,pixel_size(!ZOOM!)*0.25)) AS way,
      2 AS admin_level
    FROM ne_populated_places
    WHERE way && !BBOX!
  """

[[providers.layers]]
  name = "lz_boundaries"
  geometry_fieldname = "way"
  geometry_type = "LineString"
  # The SQL for boundaries is fairly complex because it deduplicates overlapping
  # lines, To do this, the boundary linestrings need to be turned into two-point
  # segments, distinct segments found, and then the result rebuilt into longer
  # linestrings. Tegola #559 prevents the use of CTEs, so this needs to be done
  # with nested subselects which are messier.
  # References:
  # - http://blog.cleverelephant.ca/2015/02/breaking-linestring-into-segments.html
  sql = """
  SELECT
      ST_AsBinary(ST_RemoveRepeatedPoints(
        (ST_Dump(ST_LineMerge(ST_Collect(way)))).geom,
        pixel_size(!ZOOM!)*0.25)) AS way,
      admin_level,
      osm_id
    FROM
    (SELECT
        DISTINCT ON (way) -- Select only one of the overlapping geoms
        way,
        admin_level,
        osm_id
      FROM
      (SELECT
          ST_MakeLine(
            lag((pt).geom) OVER (PARTITION BY ctid ORDER BY ctid, (pt).path),
            (pt).geom) AS way, -- This makes a line between the previous point and the next one
          admin_level,
          osm_id
        FROM
        (SELECT
            ctid,
            ST_DumpPoints(way) AS pt,
            admin_level,
            osm_id
          FROM
          (SELECT -- The innermost select just gets the admin boundaries
              ctid, -- ctid is kept around as a unique id because osm_id is not unique with long line splitting
              way,
              admin_level::integer,
              osm_id
            FROM planet_osm_roads
            WHERE way && !BBOX!
              AND boundary = 'administrative'
              AND admin_level IN ('0', '1', '2', '3', '4')
              AND osm_id < 0
          ) boundaries
        ) AS dumps
      ) AS segments
      WHERE way IS NOT NULL
      ORDER BY
        way,
        admin_level,
        osm_id
    ) AS deduplicated_segments
    GROUP BY
      osm_id,
      admin_level
  """

[[providers.layers]]
  name = "boundaries"
  geometry_fieldname = "way"
  geometry_type = "LineString"
  # This query is the same as the lz_boundaries layer, except it selects from
  # planet_osm_line and different admin_levels
  sql = """
  SELECT
      ST_AsBinary(ST_RemoveRepeatedPoints(
        (ST_Dump(ST_LineMerge(ST_Collect(way)))).geom,
        pixel_size(!ZOOM!)*0.25)) AS way,
      admin_level,
      osm_id
    FROM
    (SELECT
        DISTINCT ON (way) -- Select only one of the overlapping geoms
        way,
        admin_level,
        osm_id
      FROM
      (SELECT
          ST_MakeLine(
            lag((pt).geom) OVER (PARTITION BY ctid ORDER BY ctid, (pt).path),
            (pt).geom) AS way, -- This makes a line between the previous point and the next one
          admin_level,
          osm_id
        FROM
        (SELECT
            ctid,
            ST_DumpPoints(way) AS pt,
            admin_level,
            osm_id
          FROM
          (SELECT -- The innermost select just gets the admin boundaries
              ctid, -- ctid is kept around as a unique id because osm_id is not unique with long line splitting
              way,
              admin_level::integer,
              osm_id
            FROM planet_osm_line
            WHERE way && !BBOX!
              AND boundary = 'administrative'
              AND (admin_level IN ('0', '1', '2', '3', '4', '5', '6')
                OR admin_level IN ('7', '8') AND !ZOOM! >= 10)
              AND osm_id < 0
          ) boundaries
        ) AS dumps
      ) AS segments
      WHERE way IS NOT NULL
      ORDER BY
        way,
        admin_level,
        osm_id
    ) AS deduplicated_segments
    GROUP BY
      osm_id,
      admin_level
  """

[[providers.layers]]
  name = "buildings"
  geometry_fieldname = "way"
  geometry_type = "Polygon"
  sql = """
  SELECT
      ST_AsBinary(way) AS way,
      osm_id
    FROM planet_osm_polygon
    WHERE way && !BBOX!
      AND building IS NOT NULL
      AND building != 'no'
      AND way_area > pixel_area(!ZOOM!)*0.25
  """

[[providers.layers]]
  name = "transport"
  geometry_fieldname = "way"
  geometry_type = "LineString"
  sql = """
  SELECT
      ST_AsBinary(way) AS way,
      osm_id,
      CASE WHEN substr(highway, length(highway)-4, 5) = '_link' THEN substr(highway, 0, length(highway)-4) ELSE highway END AS highway, -- strip link,
      railway,
      name,
      ref,
      substr(highway, length(highway)-4, 5) = '_link' AS link,
      LEAST(GREATEST(COALESCE(layer, 0), -5), 5) AS layer, -- cap layer to within +/- 5
      (z_order/10)::integer + CASE WHEN substr(highway, length(highway)-4, 5) = '_link' THEN 14 ELSE 0 END AS z_order,
      -- Take z_order, scale it, then make links match z_order of non-link type
      bridge IS NOT NULL AND bridge != 'no' AS bridge,
      tunnel IS NOT NULL AND tunnel != 'no' AS tunnel
    FROM planet_osm_line
    WHERE way && !BBOX!
      AND (highway IN ('motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link',
                       'secondary', 'secondary_link')
        OR highway IN ('tertiary', 'tertiary_link') AND !ZOOM! >= 11
        OR highway IN ('unclassified', 'residential') AND !ZOOM! >= 12
        OR highway IN ('service') AND !ZOOM! >= 14
        OR railway IN ('rail', 'narrow_gague', 'funicular'))
    ORDER BY LEAST(GREATEST(COALESCE(layer, 0), -5), 5) DESC, z_order DESC
  """

[[maps]]
  name = "spirit"

[[maps.layers]]
  name = "water"
  provider_layer = "osm2pgsql.ne_water"
  min_zoom = 0
  max_zoom = 5
[[maps.layers]]
  name = "water"
  provider_layer = "osm2pgsql.lz_water"
  min_zoom = 6
  max_zoom = 9
  dont_simplify = true
[[maps.layers]]
  name = "water"
  provider_layer = "osm2pgsql.water"
  min_zoom = 10
  dont_simplify = true

[[maps.layers]]
  name = "water_names"
  provider_layer = "osm2pgsql.water_names"
  min_zoom = 6
  dont_simplify = true

[[maps.layers]]
  name = "waterways"
  provider_layer = "osm2pgsql.waterways"
  min_zoom = 8
  dont_simplify = true

[[maps.layers]]
  name = "landcover"
  provider_layer = "osm2pgsql.landcover"
  min_zoom = 6
  dont_simplify = true

[[maps.layers]]
  name = "parks"
  provider_layer = "osm2pgsql.parks"
  min_zoom = 6
  dont_simplify = true


[[maps.layers]]
  name = "boundaries"
  provider_layer = "osm2pgsql.ne_boundaries"
  min_zoom = 0
  max_zoom = 3
  dont_simplify = true
[[maps.layers]]
  name = "boundaries"
  provider_layer = "osm2pgsql.lz_boundaries"
  min_zoom = 4
  max_zoom = 7
  dont_simplify = true
[[maps.layers]]
  name = "boundaries"
  provider_layer = "osm2pgsql.boundaries"
  min_zoom = 8
  dont_simplify = true

[[maps.layers]]
  name = "buildings"
  provider_layer = "osm2pgsql.buildings"
  min_zoom = 13
  dont_simplify = true

[[maps.layers]]
  name = "transport"
  provider_layer = "osm2pgsql.transport"
  min_zoom = 10
  dont_simplify = true
